---
- hosts: webservers
  become: yes
  tasks:
     - name: Enabling port 8080 in ports.conf file
       lineinfile: path=/etc/apache2/ports.conf regexp="^Listen=" line="Listen 8080"
     - name: restart apache2 Service
       service: 
        name: apache2
        state: restarted
     - name: verify service status
       command: systemctl status apache2
       ignore_errors: yes
       changed_when: false
     - name: checking whether port 8080 is listening
       wait_for: 
         port: 8080
         delay: 5
         timeout: 5
         msg: "Timeout waiting for port 8080"
       register: port_check
       ignore_errors: yes

     - name: Revert the change made in port number
       lineinfile: path=/etc/apache2/ports.conf regexp="^Listen=" line="Listen 8080"
       when: port_check.failed == true
       
...
