---
- hosts: webservers
  become: yes
  vars:
    # created with:
    # python -c 'import crypt; print crypt.crypt("This is my Password", "$1$SomeSalt$")'
  - password: $1$SomeSalt$8x.YpfZehYFKqA1q5Qlrh/
  tasks:
     - name:  Update root password
       user: name=root update_password=always password={{password}}
...
