---
- hosts: webservers
  become: yes
  tasks:
        - cron:
            name: Weekly Server Reboot
            user: root
            hour: 5
            minute: 45
            weekday: 3 
            job: "sleep 5 && reboot"
...
